//Constants.h
#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define UWM_FOREGND_MEASUREMENT_AVAILABLE	(WM_USER + 1)
#define UWM_BKGND_MEASUREMENT_AVAILABLE		(WM_USER + 2)
#define UWM_FOREGND_MEASUREMENT_STOPPED		(WM_USER + 3)
#define UWM_COMMAND_BUSY					(WM_USER + 4)
#define UWM_APPLICATION_STATE_CHANGED		(WM_USER + 5)
#define UWM_STATUS_CHANGED					(WM_USER + 6)
#define UWM_CHANGE_OCCURED					(WM_USER + 7)
#define UWM_SEARCH_CMD_FIRED				(WM_USER + 8)
#define UWM_CONNECT_LISTENER_FIRED			(WM_USER + 9)
#define UWM_COMMAND_FAILED					(WM_USER + 10)
#define UWM_UPDATE_CMDSEQ_STATUS			(WM_USER + 11)
#define UWM_ON_SMXEXCEPTION					(WM_USER + 12)
#define UWM_CONNECT_FAILED					(WM_USER + 13)
#define UWM_RUN_AUTO_COMP_CHANGE_EVENT_FIRED (WM_USER + 23)


enum TRACKERCOMMANDS
{
	NONE,
	CONNECT,
	DISCONNECT,
	IS_INITIALIZED,
	INITIALIZE,
	MOTORS_ON,
	TURN_MOTORS_ON,
	TRACKING_ON,
	TURN_TRACKING_ON,
	TARGET_PRESENT,
	DISTANCE_VALID,	
	HOME,
	CMD_SEQUENCE,
	SEARCH,
	ABORT,
	AVAILABLE_APPS,
	RUN_APP,	
	STOP_APPS,
	FOREGND_MEASURE,
	BACKGND_MEASURE,
	SIGHT_MODE,
	SUSPEND,
	RESUME,
	DONE,
	EXIT,
	COMBO_SEARCH_1,
	COMBO_SEARCH_2,
	TOTAL_COMMANDS
};

typedef struct 
{
	char* keyword;
	double diameter;
} TARGET_INFO;

static TARGET_INFO targets[] =
{
	{ "SMR 0.500 in", 0.0127   },//1/2
	{ "SMR 0.875 in", 0.022225 },//7/8
	{ "SMR 1.500 in", 0.0381   },//3/2	
};
#endif
